In [2]:
import numpy as np
from bokeh.plotting import figure, show, output_notebook
output_notebook()

Loading BokehJS ...

In [5]:
def f(x):
    return np.sin(x)

x = np.arange(-np.pi, np.pi, .1)
p=figure()
p.line(x, f(x), color='black')
p.line(x, np.cos(x))
show(p)

In [6]:
#x = [xinic, xinic, f(xinic), f(xinic), f(f(xinic)), f(f(xinic))] , y = [0, f(xinic), f(xinic), f(f(xinic)), f(f(xinic)), f(f(f(xinic)))]

In [7]:
z1 = [1,2,3,4,5]
z2 = list(zip(z1, z1))
z3 = np.array(z2).flatten()  # flatten="aplanar", deja un arreglo uni-dimensional
print(type(z3)) # tipo de dato de la estructura z3
print(z3.dtype) # tipo de dato de cada elemento
print(z3.ndim)  # número de dimensiones de z3
print(z3)
np.concatenate(([0], z3[:-1]))

<class 'numpy.ndarray'>
int64
1
[1 1 2 2 3 3 4 4 5 5]


array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [8]:
z1

[1, 2, 3, 4, 5]

In [9]:
np.array(list(zip(z1, z1))).flatten()

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [10]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
def telaraña(f, x, xiniciales, n=20):
    "Dibuja el diagrama de telaraña de f sobre el arreglo x, con valor(es) inicial(es) xinic."
    "grafica la función sobre x"
    p=figure()
    p.line(x, f(x), color='black')
    "diagonal"
    p.line(x, x, color="red")
    def iteraciones(xinic):
        "iteraciones"
        x1 = [xinic]
        for _ in range(n//2):
            x1.append(f(x1[-1]))
        "duplicando x1"
        x2 = list(zip(x1, x1)) # duplica con zip y convierte el resultado en lista
        x3 = np.array(x2).flatten() # crea el arreglo y lo hace uni-dimensional
        "construyendo y"
        y1 = f(x3)
        y3 = np.concatenate(([0], y1[:-1])) 
        p.line(x3, y3)
    if isinstance(xiniciales, float):
        iteraciones(xiniciales)
    else:
        for xi in xiniciales:
            iteraciones(xi)
    show(p)

In [14]:
def logística(x, r=4):
    return r * x*(1-x)

x = np.arange(0, 1, .01)

telaraña(logística, x, .6, n=200)

In [15]:
telaraña(lambda x:x/2, np.arange(-1,1,.01), [-1, 1])

In [16]:
np.max(x)

0.99

In [17]:
x

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])